/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.animalworld.mousePopulationUI;

import animalworld.com.animalworld.mousePopulationInterfaces.IMousePopulationBusiness;
import com.animalworld.dto.PopulationDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author A196928
 */
public class AnimalWorldFrame extends javax.swing.JFrame {

    /**
     * Creates new form animalWorldFrame
     */
    public AnimalWorldFrame() {
        initComponents();
        
        
       findPopulationButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                
                
                PopulationDTO pop = business.loadPopulation(null);
                
                popDays.setText( (new Integer(pop.getDays())).toString());
                popManager.setText(pop.getManager());
                popName.setText(pop.getName());
                 
            }
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        findPopulationPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        popManager = new javax.swing.JTextField();
        popDays = new javax.swing.JTextField();
        popName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        findPopulationButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        createPopulationPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createVirtualPopulationPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateMouse = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("population name");

        jLabel2.setText("days");

        jLabel9.setText("manager");

        popManager.setEditable(false);
        popManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popManagerActionPerformed(evt);
            }
        });

        popDays.setEditable(false);
        popDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popDaysActionPerformed(evt);
            }
        });

        popName.setEditable(false);
        popName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popNameActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        findPopulationButton.setText("find");
        findPopulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findPopulationButtonActionPerformed(evt);
            }
        });

        cleanButton.setText("clean");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(findPopulationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(cleanButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(findPopulationButton)
                .addComponent(cleanButton))
        );

        javax.swing.GroupLayout findPopulationPanelLayout = new javax.swing.GroupLayout(findPopulationPanel);
        findPopulationPanel.setLayout(findPopulationPanelLayout);
        findPopulationPanelLayout.setHorizontalGroup(
            findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPopulationPanelLayout.createSequentialGroup()
                .addGroup(findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(findPopulationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, findPopulationPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(popName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popManager, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(72, 72, 72)
                        .addGroup(findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(popDays, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(457, Short.MAX_VALUE))
        );
        findPopulationPanelLayout.setVerticalGroup(
            findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPopulationPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(findPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(642, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("findPopulation", findPopulationPanel);

        jLabel3.setText("jLabel1");

        jLabel4.setText("jLabel2");

        javax.swing.GroupLayout createPopulationPanelLayout = new javax.swing.GroupLayout(createPopulationPanel);
        createPopulationPanel.setLayout(createPopulationPanelLayout);
        createPopulationPanelLayout.setHorizontalGroup(
            createPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPopulationPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPopulationPanelLayout.createSequentialGroup()
                .addContainerGap(972, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(337, 337, 337))
        );
        createPopulationPanelLayout.setVerticalGroup(
            createPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPopulationPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addGap(226, 226, 226)
                .addComponent(jLabel4)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("createPopulation", createPopulationPanel);

        jLabel5.setText("jLabel1");

        jLabel6.setText("jLabel2");

        javax.swing.GroupLayout createVirtualPopulationPanelLayout = new javax.swing.GroupLayout(createVirtualPopulationPanel);
        createVirtualPopulationPanel.setLayout(createVirtualPopulationPanelLayout);
        createVirtualPopulationPanelLayout.setHorizontalGroup(
            createVirtualPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createVirtualPopulationPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createVirtualPopulationPanelLayout.createSequentialGroup()
                .addContainerGap(972, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(337, 337, 337))
        );
        createVirtualPopulationPanelLayout.setVerticalGroup(
            createVirtualPopulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createVirtualPopulationPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addGap(226, 226, 226)
                .addComponent(jLabel6)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("createVirtualPopulation", createVirtualPopulationPanel);

        jLabel7.setText("jLabel1");

        jLabel8.setText("jLabel2");

        javax.swing.GroupLayout updateMouseLayout = new javax.swing.GroupLayout(updateMouse);
        updateMouse.setLayout(updateMouseLayout);
        updateMouseLayout.setHorizontalGroup(
            updateMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateMouseLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateMouseLayout.createSequentialGroup()
                .addContainerGap(972, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(337, 337, 337))
        );
        updateMouseLayout.setVerticalGroup(
            updateMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateMouseLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel7)
                .addGap(226, 226, 226)
                .addComponent(jLabel8)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("updatePopulation", updateMouse);

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(674, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addGap(532, 532, 532))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jRadioButton1)
                .addContainerGap(603, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("mi tab 5", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popManagerActionPerformed

    private void popDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popDaysActionPerformed

    private void popNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popNameActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void findPopulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findPopulationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findPopulationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalWorldFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalWorldFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalWorldFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalWorldFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalWorldFrame().setVisible(true);
            }
        });
    }

    
    public void setBusiness(IMousePopulationBusiness mBusiness){
        business = mBusiness;
    }
    
    private IMousePopulationBusiness business;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanButton;
    private javax.swing.JPanel createPopulationPanel;
    private javax.swing.JPanel createVirtualPopulationPanel;
    private javax.swing.JButton findPopulationButton;
    private javax.swing.JPanel findPopulationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField popDays;
    private javax.swing.JTextField popManager;
    private javax.swing.JTextField popName;
    private javax.swing.JPanel updateMouse;
    // End of variables declaration//GEN-END:variables
}
